### ISSUE TITLE
removed getinfo 

### ISSUE THREAD

**Issue by laviua** [SulacoSoft/BitcoindConnector4J#9]
This call was removed in version 0.16.0. Use the appropriate fields from: 
-getblockchaininfo: blocks, difficulty, chain
-getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
-getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion

bitcoin-cli has the option -getinfo to collect and format these in the old format.

		// test connection to bitcoind
		api.getinfo();

this line should be removed, otherwise you will get 404 http code during "createConnection"

**Comment by natzei** [comment]
Hi @laviua. See commit d6db930.
